server:
  port: 8081

spring:
  application:
    name: ratescollectorservice
  profiles:
    active:
      default
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

hystrix:
  command:
      default:
        execution:
            isolation:
              thread:
                timeoutInMilliseconds: 7000

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  server:
    wait-time-in-ms-when-sync-empty: 3000

ribbon:
  eureka:
    enabled: true