server:
  port: 8888
spring:
 profiles:
   active: native
 cloud:
    config:
      server:
          native:
            searchLocations: classpath:configuration/,classpath:configuration/currencyservice,classpath:configuration/servicegateway
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

